"""Adversarial judge validation (Sprint 1.5, S14).

Perturbation generator produces synthetic (question, gold, response,
expected_correct, is_abstention) cases from REAL LoCoMo gold QA pairs via
deterministic templated string transforms -- never an LLM call, so the
perturbations themselves stay auditable and reproducible instead of being
generated by the thing being validated.

Seven classes, matching reader.py's two judge templates:
  exact_match             gold answer verbatim                        expect: correct
  paraphrase              gold value in a different carrier sentence  expect: correct
  hedged_correct          gold value wrapped in hedging language      expect: correct   [false-reject risk]
  wrong_but_topical       a different, same-category wrong value      expect: incorrect [false-accept risk]
  date_quantity_near_miss a numerically/temporally adjacent value     expect: incorrect [false-accept risk]
  flat_wrong              an unrelated, cross-category wrong value    expect: incorrect
  abstain_then_guess      a refusal that still appends a guess        expect: incorrect (abstention judge)

The two false-accept classes and the two false-reject classes are exactly
what the ≤5% gates (design_scaffold.md S14) are measured against.
"""

from __future__ import annotations

import random
import re
from dataclasses import dataclass

from cognitrace.harness.reader import judge_answer

CLASSES = (
    "exact_match", "paraphrase", "hedged_correct", "wrong_but_topical",
    "date_quantity_near_miss", "flat_wrong", "abstain_then_guess",
)

FALSE_ACCEPT_GATE_CLASSES = ("wrong_but_topical", "date_quantity_near_miss")
FALSE_REJECT_GATE_CLASSES = ("paraphrase", "hedged_correct")

_ANSWERABLE_CATEGORIES = ("single-hop", "temporal", "multi-hop", "open-domain")

_PARAPHRASE_TEMPLATES = (
    "From what I recall, the answer is {v}.",
    "{v} -- that's what the conversation says.",
    "Based on the context, it's {v}.",
    "The conversation indicates {v}.",
)
_HEDGE_TEMPLATES = (
    "I'm not 100% sure, but I believe it's {v}.",
    "It might be {v}, though I could be wrong.",
    "Possibly {v} -- that's my best guess from the context.",
    "I think it's {v}.",
)
_REFUSAL_TEMPLATES = (
    "I don't have enough information to say for sure, but maybe it's {v}.",
    "That's not stated in the conversation, though it could be {v}.",
    "I can't determine this from the context -- possibly {v}?",
)

_YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")
_INT_RE = re.compile(r"\b\d{1,3}\b")

_DEFAULT_COUNTS = {
    "exact_match": 20, "paraphrase": 20, "hedged_correct": 20,
    "wrong_but_topical": 25, "date_quantity_near_miss": 20,
    "flat_wrong": 20, "abstain_then_guess": 25,
}


@dataclass
class GoldItem:
    qid: str
    question: str
    answer: str
    category: str


@dataclass
class PerturbationCase:
    cls: str
    qid: str
    question: str
    gold: str
    response: str
    expected_correct: bool
    is_abstention: bool


def _shift_numeric_or_date(value: str, rng: random.Random) -> str | None:
    """A genuine near-miss on the item's OWN value when it contains a year
    or a small integer; None (caller falls back) otherwise -- free-text
    conversational gold isn't always numeric."""
    m = _YEAR_RE.search(value)
    if m:
        year = int(m.group(0))
        return value[: m.start()] + str(year + rng.choice([-1, 1])) + value[m.end():]
    m = _INT_RE.search(value)
    if m:
        n = int(m.group(0))
        return value[: m.start()] + str(max(0, n + rng.choice([-1, 1]))) + value[m.end():]
    return None


def _pools_by_category(tasks) -> dict[str, list[GoldItem]]:
    pools: dict[str, list[GoldItem]] = {c: [] for c in _ANSWERABLE_CATEGORIES}
    pools["adversarial"] = []
    for task in tasks:
        for q in task.questions:
            if q.category not in pools:
                continue
            if q.category != "adversarial" and not q.answer.strip():
                continue
            pools[q.category].append(GoldItem(q.qid, q.question, q.answer, q.category))
    return pools


def generate_validation_set(
    tasks, seed: int = 0, counts: dict[str, int] | None = None
) -> list[PerturbationCase]:
    """Deterministic given (tasks, seed, counts) -- the same real dataset
    always produces the same validation set, so a confusion table is
    reproducible evidence, not a one-off sample."""
    counts = counts or _DEFAULT_COUNTS
    rng = random.Random(seed)
    pools = _pools_by_category(tasks)
    for pool in pools.values():
        rng.shuffle(pool)

    all_answerable = [item for cat in _ANSWERABLE_CATEGORIES for item in pools[cat]]
    rng.shuffle(all_answerable)
    if not all_answerable:
        raise ValueError("no answerable gold items found -- is the dataset loaded?")
    if not pools["adversarial"]:
        raise ValueError("no adversarial/unanswerable gold items found for abstain_then_guess")

    idx = 0

    def _next_item() -> GoldItem:
        nonlocal idx
        item = all_answerable[idx % len(all_answerable)]
        idx += 1
        return item

    cases: list[PerturbationCase] = []

    for _ in range(counts["exact_match"]):
        item = _next_item()
        cases.append(PerturbationCase("exact_match", item.qid, item.question, item.answer,
                                       item.answer, True, False))

    for _ in range(counts["paraphrase"]):
        item = _next_item()
        tmpl = rng.choice(_PARAPHRASE_TEMPLATES)
        cases.append(PerturbationCase("paraphrase", item.qid, item.question, item.answer,
                                       tmpl.format(v=item.answer), True, False))

    for _ in range(counts["hedged_correct"]):
        item = _next_item()
        tmpl = rng.choice(_HEDGE_TEMPLATES)
        cases.append(PerturbationCase("hedged_correct", item.qid, item.question, item.answer,
                                       tmpl.format(v=item.answer), True, False))

    for _ in range(counts["wrong_but_topical"]):
        item = _next_item()
        same_cat = [x for x in pools[item.category] if x.qid != item.qid]
        other = rng.choice(same_cat) if same_cat else rng.choice(all_answerable)
        tmpl = rng.choice(_PARAPHRASE_TEMPLATES)
        cases.append(PerturbationCase("wrong_but_topical", item.qid, item.question, item.answer,
                                       tmpl.format(v=other.answer), False, False))

    for _ in range(counts["date_quantity_near_miss"]):
        item = _next_item()
        shifted = _shift_numeric_or_date(item.answer, rng)
        if shifted is None:
            temporal_pool = [x for x in pools["temporal"] if x.qid != item.qid]
            shifted = rng.choice(temporal_pool).answer if temporal_pool else item.answer
        tmpl = rng.choice(_PARAPHRASE_TEMPLATES)
        cases.append(PerturbationCase("date_quantity_near_miss", item.qid, item.question,
                                       item.answer, tmpl.format(v=shifted), False, False))

    for _ in range(counts["flat_wrong"]):
        item = _next_item()
        other_cats = [c for c in _ANSWERABLE_CATEGORIES if c != item.category and pools[c]]
        other_pool = pools[rng.choice(other_cats)] if other_cats else all_answerable
        other = rng.choice(other_pool)
        tmpl = rng.choice(_PARAPHRASE_TEMPLATES)
        cases.append(PerturbationCase("flat_wrong", item.qid, item.question, item.answer,
                                       tmpl.format(v=other.answer), False, False))

    adversarial_pool = pools["adversarial"]
    for i in range(counts["abstain_then_guess"]):
        item = adversarial_pool[i % len(adversarial_pool)]
        guess = rng.choice(all_answerable).answer
        tmpl = rng.choice(_REFUSAL_TEMPLATES)
        cases.append(PerturbationCase("abstain_then_guess", item.qid, item.question, item.answer,
                                       tmpl.format(v=guess), False, True))

    return cases


def run_validation(cases: list[PerturbationCase], judge_models: list[str]) -> dict[str, list[dict]]:
    """Actual network calls -- one judge_answer() per (case, judge_model),
    through the real tiered pipeline (tier-0 fires identically regardless
    of judge_model; only the LLM tier differs, which is exactly what's
    being compared)."""
    results: dict[str, list[dict]] = {}
    for jm in judge_models:
        rows = []
        for case in cases:
            jr = judge_answer(case.question, case.gold, case.response,
                               is_abstention=case.is_abstention, model=jm)
            rows.append({
                "cls": case.cls, "qid": case.qid, "expected_correct": case.expected_correct,
                "actual_correct": jr.correct, "tier": jr.tier, "raw": jr.raw,
            })
        results[jm] = rows
    return results


def confusion_tables(results: dict[str, list[dict]]) -> dict[str, dict[str, dict]]:
    tables: dict[str, dict[str, dict]] = {}
    for jm, rows in results.items():
        per_class = {}
        for cls in CLASSES:
            crows = [r for r in rows if r["cls"] == cls]
            n = len(crows)
            false_accept = sum(1 for r in crows if not r["expected_correct"] and r["actual_correct"])
            false_reject = sum(1 for r in crows if r["expected_correct"] and not r["actual_correct"])
            per_class[cls] = {
                "n": n,
                "false_accept_rate": (false_accept / n) if n else None,
                "false_reject_rate": (false_reject / n) if n else None,
            }
        tables[jm] = per_class
    return tables


def gate_check(tables: dict[str, dict[str, dict]]) -> dict[str, dict]:
    """S14: <=5% false-accept on wrong-but-topical + date/quantity;
    <=5% false-reject on paraphrase/hedged. Judged on the WORST of the
    relevant classes, not their average -- a gate that averages away a
    bad class isn't a gate."""
    verdicts: dict[str, dict] = {}
    for jm, per_class in tables.items():
        fa_rates = [per_class[c]["false_accept_rate"] for c in FALSE_ACCEPT_GATE_CLASSES
                    if per_class[c]["false_accept_rate"] is not None]
        fr_rates = [per_class[c]["false_reject_rate"] for c in FALSE_REJECT_GATE_CLASSES
                    if per_class[c]["false_reject_rate"] is not None]
        fa_max = max(fa_rates) if fa_rates else None
        fr_max = max(fr_rates) if fr_rates else None
        verdicts[jm] = {
            "false_accept_max": fa_max,
            "false_reject_max": fr_max,
            "passes_false_accept_gate": fa_max is not None and fa_max <= 0.05,
            "passes_false_reject_gate": fr_max is not None and fr_max <= 0.05,
        }
        verdicts[jm]["passes"] = (
            verdicts[jm]["passes_false_accept_gate"] and verdicts[jm]["passes_false_reject_gate"]
        )
    return verdicts
